install:
  - choco install gitversion.portable -y
  
image: Visual Studio 2019
  
assembly_info:
  patch: false

platform:
  - Any CPU

configuration:
  - Debug

build_script:
  - cmd: nuget restore src/PullRequestReleaseNotes.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo 
  - cmd: msbuild src/PullRequestReleaseNotes.sln "/p:Configuration=%CONFIGURATION%;Platform=%PLATFORM%" 
  - cmd: xcopy /S /Y src\PullRequestReleaseNotes\bin\Debug\net472 build\NuGetExeBuild\tools\
  - cmd: xcopy /S /Y src\PullRequestReleaseNotes\NuGetAssets build\NuGetExeBuild\
  - cmd: del build\NuGetExeBuild\tools\*.dll /F /Q
  - cmd: choco pack build\NuGetExeBuild\PullRequestReleaseNotes.nuspec --outputdirectory build\NuGetExeBuild version=%GitVersion_NuGetVersion%
  - cmd: appveyor PushArtifact "build\NuGetExeBuild\PullRequestReleaseNotes.%GitVersion_NuGetVersion%.nupkg"

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified